### ISSUE TITLE
My test reroute dont work 

### ISSUE THREAD

**Issue by OleOldhoj** [nystudio107/craft-retour#116]
Here can you see the setup 

![image](https://user-images.githubusercontent.com/907322/82666414-7b74b780-9c68-11ea-826d-3cf52695541b.png)
can it be one of the other plugins that makes the error ? 

I tried with my first test 
/version1 to /version

**Comment by khalwat** [comment]
I'm not really sure what you're asking me, however you don't need to have Site Redirects and 404 Monitor and Retour installed at the same time.

Retour does what 404 Monitor and Site Redirects does.

Retour only operates once Craft throws a 404. It works this way so that it is performant.

In order for Retour to do anything, the route you're redirecting from must throw a 404 -- if it is handled by Craft, Retour never sees it.
