### ISSUE TITLE
Doesn't support league/csv 9.x

### ISSUE THREAD

**Issue by degraaf** [nystudio107/craft-retour#127]
### Describe the bug
I installed Retour (3.1.5) and attempted to import CSV.

It appears the latest version is not compatible with later versions of league/csv, which may have been installed as a requirement of another composer package.

The league site says $csv->setOffset and $csv->each are no longer supported.
https://csv.thephpleague.com/9.0/upgrading/

### To reproduce
Steps to reproduce the behaviour:
1. From Redirects page, Click Import CSV
2. Select CSV, map columns and click Import
3. Crashed on $csv->setOffset(1); (FileController, line 99) (undefined method)

### Expected behaviour
Redirects are imported.

### Screenshots
<img width="849" alt="image" src="https://user-images.githubusercontent.com/1396033/87617000-ccc99080-c759-11ea-92cb-79b4163267c0.png">

### Versions
- Plugin version: 3.1.5
- Craft version: 3.4.27

**Comment by khalwat** [comment]
You are running a fairly old version of Retour -- can you update to the latest? It's at `3.1.40` at the moment -> https://github.com/nystudio107/craft-retour/releases

This should resolve your issue.

**Comment by kylerits** [comment]
I am currently running the latest version of retour (3.1.41). I am still having issues with this. I have a custom script on my site that is dependent on league/csv v9. Will this be updated soon?

**Comment by khalwat** [comment]
@kylerits The problem is, if I have it work with `league/csv` v9 everyone who uses things that require `league/csv` v8 will similarly break.

Feel free to start a new issue on the repo if you'd like to see this addressed in some way. The only way I can see that working is if we did something like what they do for Feed Me:

https://github.com/craftcms/feed-me/blob/develop/composer.json#L36

And then write two versions of the same code, depending on which version of `league/csv` is actually being used.

**Comment by kylerits** [comment]
I just forked it and will use that for now. I needed the fix fairly rapidly. Thank you though

**Comment by khalwat** [comment]
I filed it for you @kylerits https://github.com/nystudio107/craft-retour/issues/137
