### ISSUE TITLE
Static redirects not visible anymore in admin

### ISSUE THREAD

**Issue by petertindemans** [nystudio107/craft-retour#130]
I'm having a client with 2767 static redirects in Retour plugin. Since last week the overview shows the message: No Data Available.

Tested so far:
- Do the redirects work (yes, they do)
- Exporting data (does work)
- Does the data exist in the DB (they do in: retour_static_redirects)
- Selected the wrong site (tested all sites, no result)

In the inspector I do get this errors:
Failed to load resource: the server responded with a status of 400 (Bad Request) /admin/actions/retour/tables/redirects?sort=hitCount%257Cdesc&page=1&per_page=20&siteId=0:1 
Vuetable.vue:772 load-error Error: Request failed with status code 400

Additional information:
Craft CMS: 3.4.28.1
Retour: 3.1.39

**Comment by jellingsen** [comment]
We're experiencing the same issue in periods. I did not work for a long period, but right now it started working again. I will update with more information the next time i experience the issue. Can confirm that the redirects still work, and it seems like the dashboard and redirect admin pages are affected.

PHP: 7.4.10
Craft CMS: 3.5.8
Retour: 3.1.41

**Comment by khalwat** [comment]
I ran into something obscure related to this that was due to pagination settings that someone set in Craft. Can you check what your pagination settings are?

Specifically, what do you have set for `pageTrigger` -> https://craftcms.com/docs/3.x/config/config-settings.html#pagetrigger

**Comment by khalwat** [comment]
Tho actually, in this case, it looks like the URL has been double-encoded:

/admin/actions/retour/tables/redirects?sort=hitCount`%257C`desc&page=1&per_page=20&siteId=0:1

The `%257C` decodes to `%7C` 

Since that's still encoded, `%7C` then decodes to `|`

Check your `.htaccess` or or any server-side rewrite rules, or anything else that might be potentially rewriting or double-encoding URLs.
