### ISSUE TITLE
GraphQL: 404s incorrectly incremented for URI's that exist

### ISSUE THREAD

**Issue by OscarBarrett** [nystudio107/craft-retour#177]
### Describe the bug
When making a GraphQL request for retour redirect data, if no redirect exists then the 404 counter for the given URI is incremented, regardless of whether the URI actually exists.

### To reproduce
Steps to reproduce the behaviour:
1. Query for redirect data for an existing URI.
```
query seo($uri: String) {
  retour(uri: $uri) {
    redirectDestUrl
    redirectHttpCode
  }
}
```
2. View the stats, and see that the 404 counter has incremented.

### Expected behaviour
The relevant commit is this: https://github.com/nystudio107/craft-retour/commit/f2341083c7436fd000ed0b09cfc7b78e6753d408

That seems too simple, as it increments the 404 stats but doesn't bother to check if the URI actually corresponds to an element.

We were informed of this by a client - on the website that we built for them we are using Craft as a headless CMS and request the retour data when prerendering the page so we can handle redirects as needed. If we don't get a redirect, then we continue and request the actual content. After updating retour, the 404 counter was incrementing on pages that exist and they couldn't understand why.

### Versions
- Plugin version: 3.1.52
- Craft version: 3.6.12

**Comment by khalwat** [comment]
So the idea here is that you don't execute the GraphQL query for `retour` unless a 404 has already happened (however you define that in. your SPA).

The idea is that if you hit a route that is a 404, you can ask Retour to see if there's a redirect for it.

Retour can't really know if the URL is a 404 or not; even if we did check to see if an element exists for that route, that wouldn't handle all cases. We'd need to actually do a frontend request to see if it succeeded or 404'd.

And then even _that_ wouldn't cover all of the bases, because in a headless setup, the frontend can be anywhere, routed by anything.

Happy to discuss options, but it seems to me the best course of action here is to let your frontend determine when a 404 has happened, and only then ask Retour for a potential redirect for that route.

**Comment by OscarBarrett** [comment]
One reason why we check retour first is we may have dynamic routes separate from the URIs of specific entries and want to handle potential redirects for these before making additional requests.

Another reason is to keep the structure of our frontend as simple as possible - making the top-level App responsible for redirects, and the pages responsible for rendering content or error messages.

Currently our setup is:
- App: Retour/SEOmatic request. Perform redirect if one exists, otherwise continue render.
  - Dynamic page: Relevant requests for dynamic routes, render 404/500 if data is missing
  - URI-associated page: URI request, render 404 if not found

For all cases, we're making 2 GraphQL requests at most. 1 request if there is an existing redirect.

To refactor we would do:
- App: SEOmatic request
  - Dynamic page: Relevant requests for dynamic routes
    - If data is missing: Retour request. Perform redirect if found. Render 404/500 if data is missing.
    - Render content otherwise
  - URI-associated page: URI request
    - If not found: Retour request. Perform redirect if found. Render 404 if not found.
    - Render content otherwise

For both redirect and failure cases we're now making 3 requests, and each page needs to handle redirects rather than letting the App do it. That ends up meaning extra code to test if we're aiming for proper coverage, and extra opportunities to forget to do it for new additions.

For our current usage, ideally the increment would be guarded by a call to `Craft::$app->elements->getElementByUri` (with `enabledOnly` true). This would mean that valid URIs (according to Craft) would stop showing up as 404s, and pages unrelated to URIs would be our responsibility to add to the ignore rule. For headless use this is the closest to correct stats that could be achieved.

**Comment by khalwat** [comment]
I see where you're coming from, and it's not fun to have your app break because of an upstream change.

My concern about checking `Craft::$app->elements->getElementByUri` is that it assumes that Craft is doing any kind of frontend routing... whereas with many SPA setups that won't be the case at all.

In other words, in Craft the element might have a route of `/blog/my-cool-blog` but maybe that was the old URL when the site was served by Craft, and now that the frontend has been replaced by an SPA, the route may be entirely different. In that case, checking `Craft::$app->elements->getElementByUri` would do the opposite of what would be intended.

Now, since this is a case where we're not excluding functionality, we're only excluding whether we log 404 hits, I suppose the impact wouldn't be detrimental.

However, the way Retour inherently works (whether via Craft or via SPA) is that Retour doesn't get invoked _until a 404 has already happened_. It doesn't do any active redirecting at all.

It's a last step in the routing process, before a 404 might be shown to the user on the frontend, so that content authors have a chance to put a redirect in.

So checking for `Craft::$app->elements->getElementByUri` kind of goes against the paradigm in which Retour works.

I'm still mulling over a good approach here.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/d6cacf3a0b800563ff6bc76ce14173946e43c435

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.54”,
```
Then do a `composer clear-cache && composer update`

**Comment by OscarBarrett** [comment]
Thank you for that - I've tried it out and it's working as expected.
