### ISSUE TITLE
Importing redirects - setting default values for redirect settings

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-retour#187]
Sometimes there is no column in csv to match to "redirect type" for example. There should be option to manually set value of this setting for every imported redirect. Kinda like importing using feedme plugin works.

**Comment by khalwat** [comment]
Probably the easiest way to do this would be to import the CSV into a spreadsheet like Numbers or such, and add the column, then export the CSV from there, and import it into Retour.

**Comment by piotrpog** [comment]
@khalwat 
still, this requires opening csv in excel and manipulating it. It also requires checking value of legalcy url match type field to know that it needs to be "fullurl" or omething else.

**Comment by khalwat** [comment]
This setting defaults to `pathonly`  -- an option to manually pick the default value for every imported field if it doesn't exist is probably beyond the scope.

It also wouldn't really solve the problem, because often there will be a mix of full or path matches in any given file... so a singular default value really isn't that useful.

However, I think we can do better by simply checking if the source URL begins with `http` and if it does, set it to `fullurl`

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/0ed2b2ba719dfcc1996ad7d1d4dbbc77626c3365

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.55”,
```
Then do a `composer clear-cache && composer update`

**Comment by piotrpog** [comment]
@khalwat thanks!
