### ISSUE TITLE
More granular redirect user permissions

### ISSUE THREAD

**Issue by mattsbanner** [nystudio107/craft-retour#203]
### Is your feature request related to a problem? Please describe.
Cannot separately assign redirect permissions for 301 and 302 redirects and so some clients are incorrectly creating 301 redirects and having these picked up by search engines.

### Describe the solution you would like
It would be great if within Craft CMS user permissions, 301 and 302 redirects could be assigned separately. Giving us as an agency the ability to create 301 redirects, but limiting our clients to 302 redirects.

### Describe alternatives you have considered
Building a module to remove the 301 option from the dropdown in JS and then registering an event server side to validate. However, this may not integrate nicely with the current Craft permissions.

**Comment by khalwat** [comment]
So how would you envision this working?

Most of the time, a 301 is likely what you want -- 302 would only be used if the redirect was temporary.

But if we restricted the various status codes, it's tough to say how to do it. Because sometimes a 301 is really what you want/need, and I'd think restricting the status codes that can be set as a permission based on the _user_ might not be very useful?

**Comment by mattsbanner** [comment]
Thanks for coming back to me on this.

We often see campaign urls created (e.g. /vote) in Retour, that may then link to different voting pages across the year - this is usually where we discourage the 301. The solution to that probably isn't taking away their ability to create 301s all-together because there are certainly times where they should be able to create them.

Thinking about it, the best action might just be to better educate our clients on the purpose of each redirect code.
