### ISSUE TITLE
CSV Import Shows Blank Screen

### ISSUE THREAD

**Issue by fvaldes33** [nystudio107/craft-retour#209]
### Describe the bug
When trying to import a CSV, file is created in `storage` but `import/index` template is blank. There is a quick flash of the instructional content, but when vue loads, it's all wiped out. I thought maybe it was too many rows, but even truncated down to ~100 rows same issue.

### To reproduce
1. Click on "Import CSV File"
2. Page loads, instruction flashes, page goes blank.

### Expected behavior
We see the `import-draggable` component to map columns

### Screenshots
![blank screen](https://snipboard.io/UDZ4FN.jpg)

### Versions
- Plugin version: 3.1.65
- Craft version: 3.7.16

**Comment by khalwat** [comment]
Are there any errors in the browser's JavaScript console, or in Craft's `web.log`?

**Comment by khalwat** [comment]
Right now I'm thinking there is likely something malformed with the CSV file -- can you please attach it, or email it to me at: andrew@nystudio107.com ?

**Comment by fvaldes33** [comment]
Didn't even think of that. Just blindly trying to import a CSV provided. I downloaded the existing format and copied the legacy and new url and worked like a charm. 

This can be closed. Thank you.

**Comment by khalwat** [comment]
I'll see if I can't make it be a little smarter about malformed data. A blank screen is not good UX, imo.

**Comment by khalwat** [comment]
Fixed in: https://github.com/nystudio107/craft-retour/commit/e8797b2dcda604b6e06c9a304a24098c3c45ef7a

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.66”,
```
Then do a `composer clear-cache && composer update`

It should no longer show a blank screen if the CSV data is malformed... and it will also truncate the column names if they are super long.
