### ISSUE TITLE
Search fails with Postgres

### ISSUE THREAD

**Issue by samhernandez** [nystudio107/craft-retour#25]
Retour 3.0.9
Craft 3.0.26.1
PostgreSQL 9.6.6

On the CP Retour > Redirects page, entering a search term causes a server error. Server response for the request looks like this:

```
{"error":"SQLSTATE[42703]: Undefined column: 7 ERROR:  column \"redirectsrcurl\" does not exist\nLINE 3: WHERE (`redirectSrcUrl` LIKE '%eol%') OR (`redirectDestUrl` ...\n                ^\nHINT:  Perhaps you meant to reference the column \"retour_static_redirects.redirectSrcUrl\".\nThe SQL being executed was: SELECT *\nFROM \"retour_static_redirects\"\nWHERE (`redirectSrcUrl` LIKE '%eol%') OR (`redirectDestUrl` LIKE '%eol%')\nORDER BY \"hitCount\" DESC\nLIMIT 20"}
```

Looks like the column name needs the table prepended. So picky! :)

**Comment by khalwat** [comment]
Interesting.

**Comment by khalwat** [comment]
This is what the query looks like:

```php
        // Query the db table
        $offset = ($page - 1) * $per_page;
        $query = (new Query())
            ->from(['{{%retour_static_redirects}}'])
            ->offset($offset)
            ->limit($per_page)
            ->orderBy("{$sortField} {$sortType}");
        if ($filter !== '') {
            $query->where("`redirectSrcUrl` LIKE '%{$filter}%'");
            $query->orWhere("`redirectDestUrl` LIKE '%{$filter}%'");
        }
```

I'm a little confused, as I am specifying the table in the `from`?

**Comment by brandonkelly** [comment]
Couple things to consider with PostgreSQL:

- The column quote char is `"`, not a backtick like MySQL
- Column names are normalized to lowercase unless correctly quoted.

So that’s why your `redirectSrcUrl` column is showing up as `redirectsrcurl` in the SQL error.

Easiest way to deal with it is to use Yii’s `like` query builder condition syntax, which will auto-quote the column names for you with the correct characters, and auto-add `%`'s to the beginning/end of the search value by default.

```php
if ($filter !== '') {
    $query->where(['like', 'redirectSrcUrl', $filter]);
    $query->orWhere(['like', 'redirectDestUrl', $filter]);
}
```

See the [QueryInterface::where()](https://www.yiiframework.com/doc/api/2.0/yii-db-queryinterface#where()-detail) API docs for more info on the condition syntaxes Yii supports.

**Comment by khalwat** [comment]
Ahhh this makes sense. Thanks @brandonkelly

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/62c39361d9f81100cf39cd4488c51c9d7cec1025
