### ISSUE TITLE
Allow redirections to be reordered

### ISSUE THREAD

**Issue by tremby** [nystudio107/craft-retour#258]
### Is your feature request related to a problem? Please describe.
Redirections are tested in order. (I know it's a bit more complicated than that, but the order still matters.) Sometimes therefore match behaviour depends on the order the redirections are in. But it's impossible as far as I can tell at present to reorder them without deleting one and recreating it.

### Describe the solution you would like
It would be nice to be able to drag redirections up and down in the control panel, or to have some other way to reorder them, like "move down"/"move up" buttons.

### Describe alternatives you have considered
- Deleting and recreating redirections is what I'm currently doing.
- Could probably dig in the database and change things manually, but I wouldn't want to do this in production.

**Comment by tremby** [comment]
Huh. It turns out removing and recreating redirects was not in fact changing anything at all.

The redirections are displayed in the control panel in ID order, until the user clicks one of the column headings.

But the `getAllStaticRedirects` and `getRedirectsByMatchType` methods do not fetch them in that same order; they do `->orderBy('redirectMatchType ASC, redirectSrcMatch ASC, hitCount DESC');`, so they come back in the GQL query and for the resolver (which at at least one point loops through them) in some other order which the user has no real control over. `redirectMatchType` is exact vs regex, and `redirectSrcMatch` is pathonly vs full. So they're batched by configuration, and then in each configuration batch they're tried with the most frequently matched first.

I find this weird. It's unstable. I guess if no two of your redirection rules can ever match the same requested URL it's efficient. But with our set of redirection rules many of them can absolutely match a given requested URL.

I can in fact work around it in my implementation -- I'm handling these outside of Craft, so what I can do is reorder them on receipt by ID. That'll at least be stable. But if someone is using retour's own redirection resolution logic they wouldn't be able to do that.

You may or may not see this as a bug. I definitely see it as unexpected behaviour.

**Comment by khalwat** [comment]
Please see the discussion this FR: https://github.com/nystudio107/craft-retour/issues/74

I don't think it's correct to term it "unstable", it's not usually typical that multiple redirects will match the same incoming URL. Often times reconsidering how the rules are set up will resolve this.

Non-regex redirects are matched first, because they are the most specific, and then regex rules are done next. The latter is where potentially (depending on how the regex rules are written) the order can matter.

However, you're saying that the order returned by a GraphQL query is different from how Retour resolves them as part of a normal request. If that's the case, I agree that should be changed.

Can you clarify for me? Because the db order looks the same to me:
```php
    public function getAllStaticRedirects(int $limit = null, int $siteId = null): array
    {
        // Cache it in our class; no need to fetch it more than once
        if ($this->cachedStaticRedirects !== null) {
            return $this->cachedStaticRedirects;
        }
        // Query the db table
        $query = (new Query())
            ->from(['{{%retour_static_redirects}}'])
            ->orderBy('redirectMatchType ASC, redirectSrcMatch ASC, hitCount DESC');
```
vs.
```php
    protected function getRedirectsByMatchType(int $limit = null, int $siteId = null, string $type): array
    {
        // Query the db table
        $query = (new Query())
            ->from(['{{%retour_static_redirects}}'])
            ->orderBy('redirectMatchType ASC, redirectSrcMatch ASC, hitCount DESC');
```

?

**Comment by tremby** [comment]
No, I wasn't saying the Retour resolution order and the order they're given in GQL are different. At least not necessarily -- I wasn't trying to suggest that, but I don't know the answer. I'm not using Retour's resolution logic and while I did scan over the code, just to see how they're grabbed from the DB and then what is done with them just to see if they were being reordered in some way before being looped over, but didn't study it carefully.

When I say "unstable" I'm referring to how the order and therefore priority can suddenly change if one redirection passes another in hit count. IMO that's no good. Though maybe there's something in the code which makes it not actually matter, which I missed.

You say it's unusual to have multiple redirections which can match a given single requested URL, but I don't think that's true -- the thread you linked to is full of examples, isn't it?

Thanks for pointing out the thread where someone already did ask for this feature. I *did* search; not the right keywords I guess.

**Comment by khalwat** [comment]
So I've mulled it over for a while, and I think we are likely to go with an additional priority field, so that if you want to ensure one RegEx redirect happens before another, you can assign it a higher priority.

I think doing it this way will work better than having a GUI where you can drag to re-order the redirects, for several reasons:

* If you have a number of redirects, and create a new redirect that needs to happen before the others, that can be a really difficult (and potentially paginated) drag that you'd have to do
* This is the exceptional case; most people use only exact match redirects, upon which any kind of order or priority is pointless, and even those that use RegEx redirects, it's the exceptional case that they are written in such a way that multiple matches are possible

So we're thinking a priority field that appears only for RegEx redirects, and can be searched, sorted, etc. likely just a dropdown menu that lets you choose from 1-9 (defaulting to 5)

lmk if this works for your use-case as well (it specifically addresses the older ticket I referred you to above)

Feel free to hit me up on Discord to chat about it if you have concerns!

**Comment by khalwat** [comment]
This feature has been implemented as a "priority" field.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.5”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.7”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
...and the order is deterministic now (`hitCount` is not factored in), it sorts like this:

```php
    public function getAllStaticRedirects($limit = null, int $siteId = null): array
    {
        // Query the db table
        $query = (new Query())
            ->from(['{{%retour_static_redirects}}'])
            ->orderBy('redirectMatchType ASC, priority ASC');
```

```php
    protected function getRedirectsByMatchType(int $limit = null, int $siteId = null, string $type, bool $enabledOnly = false): array
    {
        // Query the db table
        $query = (new Query())
            ->from(['{{%retour_static_redirects}}'])
            ->orderBy('redirectMatchType ASC, priority ASC');
```
