### ISSUE TITLE
When upgrade to 4.1.20, a '/' is added / to the first char of the redirectDestUrl GraphQL value.

### ISSUE THREAD

**Issue by dande-sun** [nystudio107/craft-retour#320]
### Describe the bug
When upgrade to 4.1.20, a '/' is added `/` to the first char of the redirectDestUrl GraphQL. value.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Admin console -> GraphQL -> GraphiQL"
2. Input query on "Explore the GraphQL API", like:
`query MyQuery {
  retourResolveRedirect(uri: "/partners/sign-up") {
    redirectSrcUrlParsed
    redirectSrcUrl
    redirectSrcMatch
    redirectMatchType
    redirectHttpCode
    redirectDestUrl
    enabled
  }
  retour(uri: "/partners/sign-up") {
    redirectSrcUrlParsed
    redirectSrcUrl
    redirectSrcMatch
    redirectMatchType
    redirectHttpCode
    redirectDestUrl
    enabled
  }
}
`
3. Click 'Execute Query (Ctrl-Enter)'
4. See result message
![WeCom Screenshot_20241227112836](https://github.com/user-attachments/assets/cf0d1029-f5ab-4556-b4d1-3fabb7372caa)

### Expected behaviour
I think when the redirectDestUrl GraphQL. value is a URL, its first character cannot be a '/'.

### Screenshots
this screenshot with 4.1.20
![image](https://github.com/user-attachments/assets/a54c8a02-76fa-4976-bde9-bdb2c9fc83ca)

and this is 4.1.19
![WeCom Screenshot_20241227112958](https://github.com/user-attachments/assets/2cb100ce-4a94-4d5a-b422-c11469713ac5)

### Versions
- Plugin version: 4.1.20
- Craft version: Craft Pro 4.13.7

**Comment by khalwat** [comment]
Fixed in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.21”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.0.21”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v5 as 5.0.5”,
```
Then do a `composer clear-cache && composer update`
