### ISSUE TITLE
Missing error/warning when creating static redirects

### ISSUE THREAD

**Issue by ul8** [nystudio107/craft-retour#49]
When creating a new static redirect and setting the same value for  _Legacy URL Pattern_ and _Destination URL_ fields, saving the form will display a success message but not actually save the redirect (it does not show in retour->redirects).

It should probably show some error/warning message.

I stumbled upon this when trying to create a redirect using the retourMatch plugin function, I assumed these fields could be left with their default values (both "/" ) as the matching and replacing is done inside the plugin. Turns out this is not how it works! ;-)

**Comment by khalwat** [comment]
So it technically creates it without error, but then deletes if after it detects that you'd be creating a redirect loop.

You'll receive an error message if something in the redirect doesn't _validate_ properly, but it looks like I don't bubble down the information that the redirect was created, and then deleted because it would have created a redirect loop.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/a9c4a0c8597d80bfb9fd9868c2a49eee783b97b1
