### ISSUE TITLE
Serialization Failure

### ISSUE THREAD

**Issue by baileydoestech** [nystudio107/craft-retour#51]
We have seen the following sporadic error generated by the plugin (captured by WebPerf):

![image](https://user-images.githubusercontent.com/3185073/55064081-432c1600-5071-11e9-9426-170fb02c1358.png)

**Comment by khalwat** [comment]
The relevant code is here: https://github.com/nystudio107/craft-retour/blob/v3/src/services/Statistics.php#L288

I'm assuming that this happens when two or more concurrent PHP processes are both recording stats for the same URL concurrently.

[This](https://stackoverflow.com/questions/2596005/working-around-mysql-error-deadlock-found-when-trying-to-get-lock-try-restarti) seems relevant:

> If you are using InnoDB or any row-level transactional RDBMS, then it is possible that any write transaction can cause a deadlock, even in perfectly normal situations. Larger tables, larger writes, and long transaction blocks will often increase the likelihood of deadlocks occurring. In your situation, it's probably a combination of these.

> The only way to truly handle deadlocks is to write your code to expect them. This generally isn't very difficult if your database code is well written. Often you can just put a try/catch around the query execution logic and look for a deadlock when errors occur. If you catch one, the normal thing to do is just attempt to execute the failed query again.

**Comment by khalwat** [comment]
Can you tell me a bit more about your hosting setup @lukebailey in terms of the database server... resources, load, etc.?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/42063f0c8cc9dcfcc539b0929d0b205811076583

**Comment by baileydoestech** [comment]
If it helps then we host on AWS Elastic Beanstalk (Craft) and connect the RDS Aurora (MySQL). Assuming hosting environment not an issue though looking at the fix. Thanks

**Comment by khalwat** [comment]
Yeah, it feels lame, but... I talked to a number of people about it, and the long and the short of it is that this _can_ happen regardless of what you do.

Since it's just the statistics on a 404, I figured it's not a big deal to just ignore any errors attempting to log it, because depending on concurrency, it can happen, and it's not vital that it succeed.
