### ISSUE TITLE
[FR] Add in the ability to do dynamic redirects

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-retour#6]
Since the Retour Field has been deprecated for the 3.0.0 version, replicate its functionality in a better way, by allowing for dynamic redirects.

The user can pick the section, and then it'll create redirects for every entry in that section, allowing for the use of key data like `{{ entry.someKeyData }}` in the redirect itself.

Doing it this way will be much nicer than the old Field method (which forced it to resave all of the entries if you made any changes).

**Comment by piotrpog** [comment]
Can you please clarify how it will it work? From what i understood it will be like this:

Entry can have some field, called for example `someKeyData`. Administrator enters in that field specific ID.
When importing urls from old website we want to create redirects for, example from wordpress, we can select two columns: `old url` and blog `old id`. Then `old url` will be used to match  craft entry that have  `someKeyData` field with same value as `old id`.

Im asking because I need to import contents of old wordpress install to craft project right now (client requirements), in a way that will allow me to create redirects when Retour gets updated with this functionality.

**Comment by khalwat** [comment]
Yes, it's going to work exactly like it did for Retour for Craft 2.x, however instead of being done via a FieldType (which was a little awkward) it'll be done via a **Dynamic Redirects** sidebar.

Then in your redirects, you'll be able to have something like `{entry.keyData}` in the Legacy URL field. What Retour will do under the hood is create a redirect for each entry in your channel, and parse things as a template to insert the actual data into the Legacy URL.

**Comment by piotrpog** [comment]
Thanks for clarification!

**Comment by rbaud** [comment]
Any news on this feature?

**Comment by khalwat** [comment]
Not yet, but I'm hopeful I'll have something soonish

**Comment by khalwat** [comment]
This can be done via PHP with the events that Retour triggers

https://nystudio107.com/docs/retour/advanced.html#redirect-events
