### ISSUE TITLE
[Question] Subdomain redirect

### ISSUE THREAD

**Issue by umkasanki** [nystudio107/craft-retour#77]
I'm trying to configure redirect from subdomain 
```
from:
http://blog.tishkin.by
http://blog.tishkin.by/tags
http://blog.mysite.com/tags/testing
to:
http://tishkin.by/blog
http://tishkin.by/blog/tags
http://mysite.com/blog/tags/testing
```
I use this settings:

![изображение](https://user-images.githubusercontent.com/496132/65618835-a7e80f00-dfc7-11e9-8746-fd55b9142fc6.png)

It's working fine, but only if I have `blog.tishkin.by` in list of my sites:

![изображение](https://user-images.githubusercontent.com/496132/65619045-1cbb4900-dfc8-11e9-8a5e-e31de000953d.png)

Is it possible use subdomain redirect without adding site?
If I try to remove or disable site `blog.tishkin.by` redirect stops working..
Thanks.

**Comment by khalwat** [comment]
Probably it stops working because then Craft doesn't handle requests for that domain, and thus it won't match. So I'd just keep that domain in there if you want to do the redirects this way.

As an alternative, you can set up a second virtual host and do these redirects via Apache/Nginx or what have you.
